# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  PROJECT_ID: scum-and-villainy # TODO: update Google Cloud project id
  GAR_LOCATION: us-west4-b	 # TODO: update region of the Artifact Registry
  DEPLOYMENT_NAME: vm-image # TODO: update to deployment name
  REPOSITORY: bots # TODO: update to Artifact Registry docker repository
  IMAGE: scum-and-villainy-discord-bot

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    environment: production

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.

    # authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
        token_format: 'access_token'

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} && echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

    # Build the Docker image
    - name: Build
      run: |-
        echo "${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE}}:${{github.sha}}" && \
        docker build \
          --tag "${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.REPOSITORY}}/${{env.PROJECT_ID}}/${{env.IMAGE}}:${{github.sha}}" \
          --build-arg GITHUB_SHA="${{github.sha}}" \
          --build-arg GITHUB_REF="${{github.ref}}" \
          .
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "${{env.GAR_LOCATION}}-docker.pkg.dev/${{env.PROJECT_ID}}/${{env.REPOSITORY}}/${{env.IMAGE}}:${{github.sha}}"
